[platformio]
default_envs = esp12e

[env:esp12e]
platform = espressif8266
framework = arduino
board = esp12e
monitor_speed = 115200
upload_speed = 115200
build_flags =
  -D BRIDGE_HOSTNAME=\"rgbcube\"
  -D BRIDGE_TCP_PORT=7777
  -D BRIDGE_UART_BAUD=115200
  -D MQTT_MAX_PACKET_SIZE=2048
lib_deps =
  knolleary/PubSubClient @ ^2.8

[env:esp12e_ota]
extends = env:esp12e
upload_protocol = espota
upload_port = rgbcube
; Uncomment if BRIDGE_OTA_PASSWORD is set
; upload_flags =
;   --auth=YOUR_OTA_PASSWORD
